### PR TITLE
register stuff that the devs forgot

### PR DESCRIPTION
**Pull request by Brandonbr1**
I added a water_dragon_scale.png texture and it's item  and some stuff that the devs forgot to register

### CODE REVIEW

**Comment by Brandonbr1** [comment]
@Blackout03 hey  why was my pr closed😁?

**Comment by RaveTr** [comment]
it was already added a long time ago

**Comment by Brandonbr1** [comment]
> it was already added a long time ago

@RaveTr @Blackout03 
but there are not registered in the file for the fabric branch?

**Comment by uncertainluei** [comment]
The 1.16.5 Fabric version is both discontinued and unsupported.

**Comment by Brandonbr1** [comment]
> The 1.16.5 Fabric version is both discontinued and unsupported.

oh so pr on the fabric branch won't be merged or allowed ?

**Pull request closed without merging**
