### PR TITLE
Update Apple, Cherry, and Peach Leaves to Drop Saplings & Sticks.

### PR DESCRIPTION
**Pull request by PhweeDev**
See for yourself.

### CODE REVIEW

**Comment by PhweeDev** [comment]
p.s blackout forced me to do this so i can escape his basement.

**Comment by MysticFire262** [comment]
> p.s blackout forced me to do this so i can escape his basement.

u good?

**Comment by Blackout03** [comment]
@Phweeeee Now you will never get out...

**Comment by MysticFire262** [comment]
@Blackout03 now thats just toxic

**Comment by Blackout03** [comment]
> @Blackout03 now thats just toxic

He leaked that he was in my basement... Why would he let him out now?

**Comment by PhweeDev** [comment]
I've already called the FBI bro

**Comment by MysticFire262** [comment]
> > @Blackout03 now thats just toxic
> 
> He leaked that he was in my basement... Why would he let him out now?

idk get a heart why would u put him there in the first place

**Comment by Blackout03** [comment]
@Phweeeee You should probably make it like oak leaves, where they rarely drop the fruit when broken (with same rarity as apples from oak leaves)

**Comment by Blackout03** [comment]
> > > @Blackout03 now thats just toxic
> > 
> > 
> > He leaked that he was in my basement... Why would he let him out now?
> 
> idk get a heart why would u put him there in the first place

Fun Fact: I don't even have a basement...

**Comment by MysticFire262** [comment]
> > > > @Blackout03 now thats just toxic
> > > 
> > > 
> > > He leaked that he was in my basement... Why would he let him out now?
> > 
> > 
> > idk get a heart why would u put him there in the first place
> 
> Fun Fact: I don't even have a basement...

step one: get basement
step two: knock someone out and put them in the basement
step three when they wake up u pretend to save them and become a hero and get paid mad cash moneys

**Review by PhweeDev — COMMENTED** [review]
Updated to include apple, cherry, and peach dropping from leaves

**Comment by Blackout03** [comment]
Phwee said he tested it so should be fine... He wouldn't lie to me.. right?

**Comment by MysticFire262** [comment]
> Phwee said he tested it so should be fine... He wouldn't lie to me.. right?

yea he would never lie to u cuz hes prolly scared ur gonna put him in basement level 69

**Pull request merged**
